<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

手写一个async await的原理
<script>
    //
    //  function fn(){
    //     // await '100'
    //
    //     return new Promise((resolve,reject)=>{
    //         setTimeout(()=>{
    //             resolve('100')
    //         },2000)
    //     })
    //
    //     // console.log(1111)
    // }
    //
    // // console.log(fn().then(value=>{
    // //     console.log(value)
    // // }))
    // async function fn1(){
    //     let aa = await '100';
    //     console.log(aa)
    //     console.log(101)
    //     // return 102
    // }
    // console.log(fn1())
    //  console.log(fn1().then(value=>console.log(value)))
    // console.log('---------')
    //
    // function *my(){
    //     yield new Promise((resolve,reject)=>{
    //         setTimeout(()=>{
    //             resolve('我是yield 中的promise')
    //         },1000)
    //     })
    //     console.log('my_100')
    //     console.log("my_200")
    // }
    // console.log(my().next())
    //  console.log(my().next())
    //  console.log(my().next())
    //  console.log(my().next())



    const getData = () =>new Promise(resolve => setTimeout(() => resolve("我是ajax数据"), 1000))

    async function test() {
        const data = await getData()
        console.log('data: ', data);
        const data2 = await getData()
        console.log('data2: ', data2);
        return'success'
    }

    // test();

    // var test2 = asyncToGenerator(
    //     function* testG() {
    //         // await被编译成了yield
    //         const data = yield getData()
    //         console.log('2-data: ', data);
    //         const data2 = yield getData()
    //         console.log('2-data2: ', data2);
    //         // return 'success'
    //     }
    // // )
    // let gen = testG();
    // console.log(gen.next());
    // console.log(gen.next());
    // console.log(gen.next());
    // console.log(gen.next());
    // console.log(gen.next());
    // // testG().then(res =>console.log(res))



    function* testG(xx) {
        // await被编译成了yield
        const data = yield getData()
        console.log(xx)
        console.log('data: ', data);
        const data2 = yield getData()
        console.log('data2: ', data2);
        const data3 = yield getData();
        console.log('data3: ', data3)
        return 'success'
    }

    // var gen = testG()
    //
    // var dataPromise = gen.next().value
    //
    // dataPromise.then((value1) => {
    //     // data1的value被拿到了 继续调用next并且传递给data
    //     console.log(1,value1)
    //     var data2Promise = gen.next(value1).value;
    //     // console.log('data: ', data);
    //     // 此时就会打印出data
    //
    //     data2Promise.then((value2) => {
    //         // data2的value拿到了 继续调用next并且传递value2
    //         gen.next(value2)
    //
    //         // console.log('data2: ', data2);
    //         // 此时就会打印出data2
    //     })
    // })




    function  ToGenerator(generatorFunc) {
        // 返回的是一个新的函数
        return function() {

            // 先调用generator函数 生成迭代器
            // 对应 var gen = testG()
            const gen = generatorFunc.apply(this, arguments)
            console.dir(gen)
            // 返回一个promise 因为外部是用.then的方式 或者await的方式去使用这个函数的返回值的
            // var test = asyncToGenerator(testG)
            // test().then(res => console.log(res))
            return new Promise((resolve, reject) => {

                // 内部定义一个step函数 用来一步一步的跨过yield的阻碍
                // key有next和throw两种取值，分别对应了gen的next和throw方法
                // arg参数则是用来把promise resolve出来的值交给下一个yield
                function step(key, arg) {
                    let generatorResult

                    // 这个方法需要包裹在try catch中
                    // 如果报错了 就把promise给reject掉 外部通过.catch可以获取到错误
                    try {
                        generatorResult = gen[key](arg)
                    } catch (error) {
                        return reject(error)
                    }

                    // gen.next() 得到的结果是一个 { value, done } 的结构
                    const { value, done } = generatorResult

                    if (done) {
                        // 如果已经完成了 就直接resolve这个promise
                        // 这个done是在最后一次调用next后才会为true
                        // 以本文的例子来说 此时的结果是 { done: true, value: 'success' }
                        // 这个value也就是generator函数最后的返回值
                        return resolve(value)
                    } else {
                        // 除了最后结束的时候外，每次调用gen.next()
                        // 其实是返回 { value: Promise, done: false } 的结构，
                        // 这里要注意的是Promise.resolve可以接受一个promise为参数
                        // 并且这个promise参数被resolve的时候，这个then才会被调用
                        return Promise.resolve(
                            // 这个value对应的是yield后面的promise
                            value
                        ).then(
                            // value这个promise被resove的时候，就会执行next
                            // 并且只要done不是true的时候 就会递归的往下解开promise
                            // 对应gen.next().value.then(value => {
                            //    gen.next(value).value.then(value2 => {
                            //       gen.next()
                            //
                            //      // 此时done为true了 整个promise被resolve了
                            //      // 最外部的test().then(res => console.log(res))的then就开始执行了
                            //    })
                            // })
                            function onResolve(val) {
                                step("next", val)
                            },
                            // 如果promise被reject了 就再次进入step函数
                            // 不同的是，这次的try catch中调用的是gen.throw(err)
                            // 那么自然就被catch到 然后把promise给reject掉啦
                            function onReject(err) {
                                step("throw", err)
                            },
                        )
                    }
                }
                step("next")
            })
        }
    }

    // toMyAwait(testG)(123)


    var kk = toMyAwait(function *()
        {
            let aa = yield '10000000';
            console.log(aa)
            console.log(101000000)
                // return 102
        }
    )
    console.log(kk())

    function toMyAwait(generatorFunc){
        return function AsyncFun(){
            let gen  = generatorFunc.apply(this,arguments)   //1.改变this指向，创建一个generator，2.将参数传给generator
            return new Promise((resolve,reject)=>{
                var result ;
                function step(key='next',arg){
                    try{
                        result  = gen[key](arg)

                    }catch (e) {
                        reject(e)
                    }

                    const {value,done} = result;
                    console.log(value,done)
                    if(done){
                        resolve(value)
                    }else{
                        Promise.resolve(value).then(value=>{
                            step('next',value)
                        },err=>{
                            step('throw',err)
                        })
                    }
                }



                step("next")
            })



        }
    }

</script>
</body>
</html>
